FROM debian:bullseye

RUN apt-get update && apt upgrade -y

RUN apt-get install -y vim nginx openssl

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/mykey.key -out /etc/nginx/ssl/mycert.crt  -subj "/C=MA/ST=Khouribga/L=Khouribga/O=1337/OU=Education/CN=abelahce.42.fr"

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
